### ISSUE TITLE
Release 2.0.20 breaks when `bravado` tries to validate the swagger spec

### ISSUE THREAD

**Issue by suavesav** [launchdarkly/ld-openapi#33]
This is how I have been using`ld-openapi`
```
from bravado.client import SwaggerClient
client_api = SwaggerClient.from_url('https://launchdarkly.github.io/ld-openapi/openapi.json')
```

As of 2.0.20, it leads to this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/savinay/.pyenv/versions/2.7.14/lib/python2.7/site-packages/bravado/client.py", line 107, in from_url
    return cls.from_spec(spec_dict, spec_url, http_client, config)
  File "/Users/savinay/.pyenv/versions/2.7.14/lib/python2.7/site-packages/bravado/client.py", line 134, in from_spec
    spec_dict, origin_url, http_client, config,
  File "/Users/savinay/.pyenv/versions/2.7.14/lib/python2.7/site-packages/bravado_core/spec.py", line 185, in from_dict
    spec.build()
  File "/Users/savinay/.pyenv/versions/2.7.14/lib/python2.7/site-packages/bravado_core/spec.py", line 197, in build
    self._validate_spec()
  File "/Users/savinay/.pyenv/versions/2.7.14/lib/python2.7/site-packages/bravado_core/spec.py", line 193, in _validate_spec
    http_handlers=self.get_ref_handlers(),
  File "/Users/savinay/.pyenv/versions/2.7.14/lib/python2.7/site-packages/swagger_spec_validator/validator20.py", line 163, in validate_spec
    http_handlers=http_handlers,
  File "/Users/savinay/.pyenv/versions/2.7.14/lib/python2.7/site-packages/swagger_spec_validator/common.py", line 29, in wrapper
    sys.exc_info()[2])
  File "/Users/savinay/.pyenv/versions/2.7.14/lib/python2.7/site-packages/swagger_spec_validator/common.py", line 24, in wrapper
    return method(*args, **kwargs)
  File "/Users/savinay/.pyenv/versions/2.7.14/lib/python2.7/site-packages/swagger_spec_validator/validator20.py", line 215, in validate_json
    cls=Draft4Validator,
  File "/Users/savinay/.pyenv/versions/2.7.14/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 52, in validate
    instance_cls(schema, *args, **kwargs).validate(instance)
  File "/Users/savinay/.pyenv/versions/2.7.14/lib/python2.7/site-packages/jsonschema/validators.py", line 353, in validate
    raise error
swagger_spec_validator.common.SwaggerValidationError: ("{u'description': u'Returns timeseries data and all sdk versions.', u'schema': {u'x-scope': ['https://launchdarkly.github.io/ld-openapi/openapi.json'], u'$ref': u'#/definitions/MAUbyCategory'}} is not valid under any of the given schemas\n\nFailed validating 'oneOf' in schema['properties']['paths']['patternProperties']['^/']['properties']['get']['properties']['responses']['patternProperties']['^([0-9]{3})$|^(default)$']:\n    {'oneOf': [{'$ref': '#/definitions/response'},\n               {'$ref': '#/definitions/jsonReference'}]}\n\nOn instance['paths'][u'/usage/mau/bycategory']['get']['responses'][u'200']:\n    {u'description': u'Returns timeseries data and all sdk versions.',\n     u'schema': {u'$ref': u'#/definitions/MAUbyCategory',\n                 u'x-scope': ['https://launchdarkly.github.io/ld-openapi/openapi.json']}}", <ValidationError: "{u'description': u'Returns timeseries data and all sdk versions.', u'schema': {u'x-scope': ['https://launchdarkly.github.io/ld-openapi/openapi.json'], u'$ref': u'#/definitions/MAUbyCategory'}} is not valid under any of the given schemas">)
```

The work around for now is to set `validate_swagger_spec = False` like this:
```
from bravado.client import SwaggerClient
OPTS = { 'validate_swagger_spec': False }
client_api = SwaggerClient.from_url(
    'https://launchdarkly.github.io/ld-openapi/openapi.json',
    config=OPTS
)
```

The error is indicating that the issue is here: https://github.com/launchdarkly/ld-openapi/commit/a7072c8c5f4fe0e0536314408fee75882aa4425b#diff-8d2741e7ceded60530075c3064376672R71

**Comment by bwoskow-ld** [comment]
Hi @suavesav ,

I'm able to reproduce this issue. We'll get it fixed right away such that the spec validates.

Ben

[tracked internally as 55632]

**Comment by bwoskow-ld** [comment]
2.0.21 has been released with the validation fixes. I verified that https://launchdarkly.github.io/ld-openapi/openapi.json properly validates.

Let me know if there's anything else we can help with.

**Comment by suavesav** [comment]
Thanks! Verified that 2.0.21 fixes the issue.
