### ISSUE TITLE
Python SDK does not work with Python 3.7

### ISSUE THREAD

**Issue by levlaz** [launchdarkly/ld-openapi#8]
Per https://docs.python.org/3/whatsnew/3.7.html `async` is now a reserved keyword. This causes the generated client to break when using `python 3.7` with the following error message. 

```
(venv) ld-mbp:SupportService levlaz$ python cli.py
Traceback (most recent call last):
  File "cli.py", line 1, in <module>
    from launchdarkly_api import Configuration, ProjectsApi, ApiClient
  File "/Users/levlaz/git/SupportService/lib/api-client-python/launchdarkly_api/__init__.py", line 19, in <module>
    from launchdarkly_api.api.audit_log_api import AuditLogApi
  File "/Users/levlaz/git/SupportService/lib/api-client-python/launchdarkly_api/api/__init__.py", line 6, in <module>
    from launchdarkly_api.api.audit_log_api import AuditLogApi
  File "/Users/levlaz/git/SupportService/lib/api-client-python/launchdarkly_api/api/audit_log_api.py", line 139
    async=params.get('async'),
        ^
SyntaxError: invalid syntax
```

**Comment by ashanbrown** [comment]
This was filed as an issue on swagger-codegen at https://github.com/swagger-api/swagger-codegen/issues/8328.  There is a fix for codegen 3.x but I'm not sure if it will be backported to 2.3.x.  We might need to put in a workaround because we cannot switch to codegen 3.x yet (because some targets are not available yet, such as javascript).

**Comment by ashanbrown** [comment]
@levlaz We upgraded to codegen 2.4.0 which we believe has fixed this problem.  LMK if it is still a problem.  Thanks.
